import Head from "next/head";
import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";

export default function Home({ posts }) {
  return (
    <div className="">
      <Head>
        <title>Yuvi's Personal Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="logo" href="/logo.png" />
      </Head>

      <main>
        <div className="p-10">
          {posts.map((post) => {
            return (
              <Link key={`${post.slug}`} href={`/blog/${post.slug}`}>
                <a>
                  <div className="flex flex-col items-center mb-6 bg-white rounded-lg border md:flex-row md:max-w-xl">
                    <img
                      className="object-cover w-full h-full md:h-auto md:w-48 "
                      src={`${post.frontMatter.socialImage}`}
                      alt="thumbnail"
                    />
                    <div className="flex flex-col justify-between p-4 leading-normal">
                      <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-black">
                        {post.frontMatter.title}
                      </h5>
                      <p className="mb-3 italic text-gray-700 dark:text-gray-400 text-sm">
                        {post.frontMatter.metaTitle}
                      </p>
                      <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
                        {post.frontMatter.metaDesc}
                      </p>
                      <p className="mb-3 font-normal text-gray-700 dark:text-gray-400">
                        {post.frontMatter.date}
                      </p>
                      <p className="flex mb-3 font-normal text-gray-700 dark:text-gray-400">
                        {post.frontMatter.tags}
                      </p>
                    </div>
                  </div>
                </a>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  // Get the posts
  const files = fs.readdirSync("posts");
  const posts = files.map((filename) => {
    const slug = filename.replace(".md", "");
    const readFiles = fs.readFileSync(`posts/${filename}`);
    const { data: frontMatter } = matter(readFiles);
    return {
      slug,
      frontMatter,
    };
  });
  return {
    props: {
      posts,
    },
  };
}
